Introduced async I/O support with io_uring on Linux, disabled musllinux builds because io_uring requires glibc, and adjusted Docker image accordingly.

diff --git a/.github/workflows/build-and-release-python-client-wheels-and-sdist.yml b/.github/workflows/build-and-release-python-client-wheels-and-sdist.yml
--- a/.github/workflows/build-and-release-python-client-wheels-and-sdist.yml
+++ b/.github/workflows/build-and-release-python-client-wheels-and-sdist.yml
@@ -125,104 +125,104 @@ jobs:
           path: dist
 
 
-  musllinux:
-    runs-on: ${{ matrix.platform.runner }}
-    env:
-      PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.10"]
-        platform:
-          - runner: ubuntu-22.04
-            target: x86_64
-            test-on-docker-platform: linux/amd64
-          - runner: ubuntu-22.04
-            target: aarch64
-            test-on-docker-platform: linux/arm64
-    #          - runner: ubuntu-22.04
-    #            target: armv7
-    steps:
-      - uses: actions/checkout@v6
-      - uses: actions/setup-python@v6
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Setup QEMU
-        if: matrix.platform.target != 'x86_64'
-        uses: docker/setup-qemu-action@v3
-
-      - name: Build wheels
-        uses: PyO3/maturin-action@v1
-        with:
-          target: ${{ matrix.platform.target }}
-          args: --release --out dist --manifest-path umadb-python/Cargo.toml -i python${{ matrix.python-version }}
-          #          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
-          manylinux: musllinux_1_2
-          before-script-linux: |
-            PROTOC_VERSION=33.1
-            case "$(uname -m)" in
-              x86_64)  PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-x86_64.zip" ;;
-              aarch64) PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-aarch_64.zip" ;;
-              armv7l)  PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-armv7.zip" ;;
-              i686)    PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-x86_32.zip" ;;
-              *) echo "Unsupported arch: $(uname -m)" >&2; exit 1 ;;
-            esac
-            curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}"
-            unzip "${PROTOC_ZIP}" -d "$HOME/protoc"
-            export PATH="$HOME/protoc/bin:$PATH"
-
-      - name: Start UmaDB server
-        run: |
-          docker network create umadb-net
-          docker run -d --network umadb-net --name umadb-server umadb/umadb:latest
-          # Wait for server to become ready
-          for i in {1..20}; do
-              if nc -z localhost 50051; then
-                  echo "UmaDB server is up!"
-                  break
-              fi
-              echo "Waiting for UmaDB server..."
-              sleep 1
-          done
-
-      - name: Test built wheel
-        uses: addnab/docker-run-action@v3
-        with:
-          image: python:3.10-alpine
-          options: |
-            -v ${{ github.workspace }}/dist:/dist
-            --platform ${{ matrix.platform.test-on-docker-platform }}
-            --network umadb-net
-          run: |
-            pip install /dist/*.whl
-            python - << 'END'
-            from umadb import Client, Event
-
-            # Connect to UmaDB server
-            client = Client("http://umadb-server:50051")
-            
-            # Create and append events
-            event = Event(
-                event_type="UserCreated",
-                data=b"user data",
-                tags=["user", "creation"],
-            )
-            position = client.append([event])
-            print(f"Event appended at position: {position}")
-            
-            # Read events
-            events = client.read()
-            for seq_event in events:
-                print(f"Position {seq_event.position}: {seq_event.event.event_type}")
-
-            END
-
-      - name: Upload artifact
-        uses: actions/upload-artifact@v6
-        with:
-          name: wheels-musllinux-${{ matrix.python-version }}-${{ matrix.platform.target }}
-          path: dist
+#  musllinux:
+#    runs-on: ${{ matrix.platform.runner }}
+#    env:
+#      PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        python-version: ["3.10"]
+#        platform:
+#          - runner: ubuntu-22.04
+#            target: x86_64
+#            test-on-docker-platform: linux/amd64
+#          - runner: ubuntu-22.04
+#            target: aarch64
+#            test-on-docker-platform: linux/arm64
+#    #          - runner: ubuntu-22.04
+#    #            target: armv7
+#    steps:
+#      - uses: actions/checkout@v6
+#      - uses: actions/setup-python@v6
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#
+#      - name: Setup QEMU
+#        if: matrix.platform.target != 'x86_64'
+#        uses: docker/setup-qemu-action@v3
+#
+#      - name: Build wheels
+#        uses: PyO3/maturin-action@v1
+#        with:
+#          target: ${{ matrix.platform.target }}
+#          args: --release --out dist --manifest-path umadb-python/Cargo.toml -i python${{ matrix.python-version }}
+#          #          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
+#          manylinux: musllinux_1_2
+#          before-script-linux: |
+#            PROTOC_VERSION=33.1
+#            case "$(uname -m)" in
+#              x86_64)  PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-x86_64.zip" ;;
+#              aarch64) PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-aarch_64.zip" ;;
+#              armv7l)  PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-armv7.zip" ;;
+#              i686)    PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-x86_32.zip" ;;
+#              *) echo "Unsupported arch: $(uname -m)" >&2; exit 1 ;;
+#            esac
+#            curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}"
+#            unzip "${PROTOC_ZIP}" -d "$HOME/protoc"
+#            export PATH="$HOME/protoc/bin:$PATH"
+#
+#      - name: Start UmaDB server
+#        run: |
+#          docker network create umadb-net
+#          docker run -d --network umadb-net --name umadb-server umadb/umadb:latest
+#          # Wait for server to become ready
+#          for i in {1..20}; do
+#              if nc -z localhost 50051; then
+#                  echo "UmaDB server is up!"
+#                  break
+#              fi
+#              echo "Waiting for UmaDB server..."
+#              sleep 1
+#          done
+#
+#      - name: Test built wheel
+#        uses: addnab/docker-run-action@v3
+#        with:
+#          image: python:3.10-alpine
+#          options: |
+#            -v ${{ github.workspace }}/dist:/dist
+#            --platform ${{ matrix.platform.test-on-docker-platform }}
+#            --network umadb-net
+#          run: |
+#            pip install /dist/*.whl
+#            python - << 'END'
+#            from umadb import Client, Event
+#
+#            # Connect to UmaDB server
+#            client = Client("http://umadb-server:50051")
+#
+#            # Create and append events
+#            event = Event(
+#                event_type="UserCreated",
+#                data=b"user data",
+#                tags=["user", "creation"],
+#            )
+#            position = client.append([event])
+#            print(f"Event appended at position: {position}")
+#
+#            # Read events
+#            events = client.read()
+#            for seq_event in events:
+#                print(f"Position {seq_event.position}: {seq_event.event.event_type}")
+#
+#            END
+#
+#      - name: Upload artifact
+#        uses: actions/upload-artifact@v6
+#        with:
+#          name: wheels-musllinux-${{ matrix.python-version }}-${{ matrix.platform.target }}
+#          path: dist
 
 
   windows:
@@ -330,7 +330,8 @@ jobs:
     name: Release
     runs-on: ubuntu-latest
     #    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
-    needs: [linux, musllinux, windows, macos, sdist]
+#    needs: [linux, musllinux, windows, macos, sdist]
+    needs: [linux, windows, macos, sdist]
     permissions:
       # Use to sign the release artifacts
       id-token: write
